name: Job Scraper

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Critical for git push

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python job_monitor.py || echo "Script exited with error, continuing..."

      # ▼▼▼ ADD THIS BLOCK RIGHT HERE ▼▼▼
      - name: Upload Debug HTML Files
        uses: actions/upload-artifact@v3
        if: always()  # Upload even if job fails
        with:
          name: debug-pages
          path: debug_page_*.html
      # ▲▲▲ ABOVE BLOCK ADDED ▲▲▲

      - name: Commit new job IDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if jobs.txt exists
          if [ -f "jobs.txt" ]; then
            git add jobs.txt
            git commit -m "Update tracked job IDs" || echo "No changes to commit"
            # Push using GITHUB_TOKEN
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin HEAD:${{ github.ref }}
          else
            echo "No jobs.txt to commit."
          fi
